# https://bytedance.feishu.cn/wiki/wikcnPgz1Cd1X0M1ph2TYynQ5cg
template: go
go_version: "1.18"
clone_depth: 1

trigger:
  change:

commands:
#  - go install gotest.tools/gotestsum@latest
  - bash .codebase/scripts/test.sh accurate
#  - bash .codebase/scripts/test.sh gotestsum
  - go tool cover -html=coverage.out -o coverage.html

post_steps:
  - name: convert report
    if: "true"
    commands:
      - go install gotest.tools/gotestsum@latest
      - gotestsum --junitfile report.xml --raw-command cat report.json
  - name: test report
    if: "true"
    uses: actions/report
    inputs:
      encoding: junit
      includes:
        - "report.xml"

coverage_report_name: coverage.html
#enable_test_report: true
#test_report_files:
#  - "report.xml"
